services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    expose:
      - 3000
    env_file:
      - .env

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"