services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env